### ISSUE TITLE
Constant disconnects

### ISSUE THREAD

**Issue by Samuron** [cody-greene/node-rabbitmq-client#12]
Hello! 
First of all I would like to thank you for the amazing work you've done on the project. I just recently migrated to this library from amqplib and for most part everything is working great. There is a strange issue however with the exclusive queues. Overall the connection is very stable for all of the services except the ones that declare one or more exclusive queus. The strange part is that they disconnect and reconnect (I use Consumer object) every 3 minutes. The error that is received is not very descriptive:
```json
{
  "level": "error",
  "time": "2023-03-29T05:58:31.599Z",
  "version": "1.0.853",
  "name": "clientbff",
  "trace_id": "2f0a4e39ee64e6862d929dd9c1359205",
  "span_id": "b19aec1f82141b19",
  "msg": "Received disconnect from RabbitMQ",
  "err": {
    "type": "Error",
    "message": "read ECONNRESET",
    "stack": "Error: read ECONNRESET\n    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)\n    at __node_internal_errnoException (node:internal/errors:620:12)\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)",
    "errno": -104,
    "code": "ECONNRESET",
    "syscall": "read"
  }
}
```
And here is the disconnect reaperring each 3 minutes.

![image](https://user-images.githubusercontent.com/9255285/228440703-bff474cb-e401-4541-942f-ed15bf2cf244.png)

And as I've told other connections are very stable except two services that user only exclusive queues
![image](https://user-images.githubusercontent.com/9255285/228441754-ff0c9cff-b74b-4321-a984-5a449809a42d.png)

Any guidance is appreciated

Update:

It seems this issue is not related to exlusive queues, but to noack mode, this is the parameter that triggeres the disconnects

**Comment by cody-greene** [comment]
I believe I found the issue. The client only sends a heartbeat frame in response to a server-sent heartbeat (thump-thump). The server only sends heartbeats when it has nothing else to send (nothing outbound). However, your combination of `noAck` and _sustained inbound messages_ means the client and server can go a long time without exchange heartbeats. Long enough for your rabbit cluster, or load balancer, to think the connection is dead. :man_facepalming: 

![image](https://user-images.githubusercontent.com/6316107/228720772-3526f3b4-fe8c-447a-a32b-2489ab8b8208.png)


Pretty big oversight on my part. I'll have add a proper heartbeat timer rather than treating it like a request-response. Should take a few days.
