### ISSUE TITLE
Connection is not a constructor

### ISSUE THREAD

**Issue by kiaxseventh** [cody-greene/node-rabbitmq-client#14]
hello dear
i can not run sample
i get error on the first line import

    

    
    const rabbit = new Connection();
               ^

    TypeError: Connection is not a constructor
    at file:///Users/kiax/xxx/src/index.mjs:1:16
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

 my node version is : v18.x

**Comment by cody-greene** [comment]
Try `import {Connection} from "rabbitmq-client"`

-------- Original Message --------

**Comment by kiaxseventh** [comment]
thank you very much

**Comment by kiaxseventh** [comment]
but it has another issue for run simple example:

**Comment by cody-greene** [comment]
You probably closing the channel before the message can be acknowledged (basicAck).

I suggest that you use [Channel.createConsumer](https://cody-greene.github.io/node-rabbitmq-client/classes/Connection.html#createConsumer) instead of the low-level `basicConsume` method. I should update the documentation to point new users toward the safer interface.

**Comment by kiaxseventh** [comment]
thanks
