### ISSUE TITLE
control acknowledgement

### ISSUE THREAD

**Issue by sherifwahballa1** [cody-greene/node-rabbitmq-client#34]
I need to know how I can prevent auto ack for the messages when I use client.createConsumer I need to control in ack the message I don't need to ack it automatically

**Comment by cody-greene** [comment]
https://cody-greene.github.io/node-rabbitmq-client/4.4.0/classes/Consumer.html
https://cody-greene.github.io/node-rabbitmq-client/4.4.0/enums/ConsumerStatus.html

> The callback can also return a numeric status code to control the ACK/NACK
> behavior. The ConsumerStatus enum is provided for convenience.
> 
> ACK/NACK behavior when the callback:
> 
>    throws an error - BasicNack(requeue=ConsumerProps.requeue)
>    returns 0 or undefined - BasicAck
>    returns 1 - BasicNack(requeue=true)
>    returns 2 - BasicNack(requeue=false)


```javascript
import {ConsumerStatus} from 'rabbitmq-client'

const sub = rabbit.createConsumer({
  queue: 'my-queue',
  requeue: false // behavior with exceptions
}, async (msg) => {
  return ConsumerStatus.ACK
  //return ConsumerStatus.REQUEUE
  //return ConsumerStatus.DROP
})
```

**Comment by morpig** [comment]
Hey @cody-greene, came across this issue. I think you misinterpret the original q.

Current behaviour is that when consumer function returns nothing/undefined, the message is ack'd automatically.

Is it possible to not ack automatically, so the expected behaviour (if nothing is returned) is ignored?

Having experience with google's pubsub, message is ack when an ack function is called only.

**Comment by cody-greene** [comment]
There is a noAck mode, but I don't think that's what you're asking for. You want to detach from the consumer, essentially, so you can manually ack at a later time?

First, changing the default behavior is a breaking change, the kind of thing I generally want to avoid. Theoretically I could add something like ConsumerStatus.NONE

But I am not convinced of the usefulness of this pattern. Why not delay your return until you're actually done with the message (async await etc)?

-------- Original Message --------

**Comment by cody-greene** [comment]
Safety is the big reason for avoiding manual acknowledgements. If the only way to ack/nack a message is to invoke a function, then what happens if your code throws an error before that happens? Ultimately the rabbitmq exchange will redeliver after some timeout but that can take a while. In contrast, this library will nack/reject the message if there's an unhandled error in your code.
