### ISSUE TITLE
 Any future additions for batch consumption?

### ISSUE THREAD

**Issue by johnatanlopes** [cody-greene/node-rabbitmq-client#35]
I have an application that receives several messages, with this library I need to search the database for each message at a time and consequently insert/update one by one. Are you thinking about adding support for batch consumer?

For example, we have prefetchCount at 100, it would take these 100 messages and pass them to the handler as an array of messages so we could work on them all at once.

It would also be nice if you use this batch to double the value of prefetchCount to have something hot in your hands.

Thank you for everything

**Comment by cody-greene** [comment]
I have no plans yet. I'll think about it. It is possible for you to add a batching layer on top of this library. The consumer handler can add messages to an in-memory queue and the actual processing can can depend on whatever delay & max/minBatchSize you wish. Resolve all the handlers together, when the batch is done.

However there are some performance reasons to do this within rabbitmq-client:
- could send a single BasicAck(multiple=true) instead of 100 acks
- may not create so many Promise objects

Some alternatives to consider:
- rabbit streams (with the stream protocol, need a different client)
- Kafka streams
- noAck=true or simply ack when adding to your in-memory batch queue (there are safety concerns here)

-------- Original Message --------

**Comment by johnatanlopes** [comment]
I believe that sending a single ack=true to all 100 would be fair, it would be the same way if an error occurs, it would return the requeue or drop to everyone.

This would help a lot to work with bulks.

Doing this will leave a path to expand to make something more optimized.
